---
- name: Load a variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: Choose platform based task
  include_tasks: '{{ platform }}'
  with_first_found:
    - 'system/{{ ansible_system }}.yml'
    - 'system/{{ ansible_os_family }}.yml'
    - 'system/not-supported.yml'
  loop_control:
    loop_var: platform
